### ISSUE TITLE
파일의 정보

### ISSUE THREAD

**Issue by jungueheon** [naniboy/Project2#1]
1. 파일의 정보엔 무엇이 있는가?
2. 우리가 필요한 정보는 무엇?
3. 어떻게 그 정보들을 받아 올 것인가?

**Comment by jungueheon** [comment]
## 1. 파일에 존재하는 속성들

- Type : 일반 파일 or 디렉토리 or 실행파일... etc
- permission : 허가권
- Size : 파일의 크기
- Time : 만들어진 시간, 최종 수정된 시간
- UID, GID : User ID, Group ID
- i-node number

등등

**Comment by jungueheon** [comment]
2. 필요한 속성
Size : 파일의 크기
Block Size : 데이터 또는 프로그램의 한 블록 크기이며, 정보를 처리하는 논리적인 단
위로 보통 레코드의 집합으로 구성됨.
시간 : 마지막으로 수정된 날짜, 시간

**Comment by jungueheon** [comment]
2-1. struct stat* : 파일의 정보가 들어가는 구조체 포인터
struct stat {
dev_t st_dev; /* ID of device containing file */
ino_t st_ino; /* inode number */
mode_t st_mode; /* protection */
nlink_t st_nlink; /* number of hard links */
uid_t st_uid; /* user ID of owner */
gid_t st_gid; /* group ID of owner */
dev_t st_rdev; /* device ID (if special file)
off_t st_size; /* total size, in bytes */
blksize_t st_blksize; /* blocksize for file system I/O */
blkcnt_t st_blocks; /* number of 512B blocks
allocated */
time_t st_atime; /* time of last access */
time_t st_mtime; /* time of last modification */
time_t st_ctime; /* time of last status change */
};

**Comment by jungueheon** [comment]
2-2. 필요한 정보
struct stat {
off_t st_size; //파일의 총 크기
blkcnt_t st_blocks; //512Byte block의 개수
time_t st_mtime; //마지막 수정 시간
};

**Comment by jungueheon** [comment]
3. HOW?
- 정보 : stat() = 파일의 정보를 받아오는 함수.
- 시간 : localtime() = time_t값을(calender time) broken-down time으로 바꿔주는 함수.

**Comment by jungueheon** [comment]
3-1. stat() 함수
기본 형 : int stat(const char *path, struct stat *buf);
const char *path : 파일의 경로
struct stat *buf : 파일의 정보가 들어가는 구조체

**Comment by jungueheon** [comment]
3-2. localtime() 함수
##  - 기본 형 : struct tm *localtime(const time_t *temp);
##  - const time_t *temp : time_t형 변수를 가리키는 포인터
위 stat()함수로 정보를 받아온 후 인자로 사용한다.
## - struct tm* localtime : 시간 정보가 들어가는 구조체 포인터
struct tm* localtime{
int tm_sec; /* seconds */
int tm_min; /* minutes */
int tm_hour; /* hours */
int tm_mday; /* day of the month */
int tm_mon; /* month */
int tm_year; /* year */
}

**Comment by tennisjeong** [comment]
수고했습니다 .혹시 다른 속성정보는 없나요?
