### ISSUE TITLE
2. 필요한 속성들

### ISSUE THREAD

**Issue by jungueheon** [naniboy/Project2#8]
- Size : 파일의 크기
- Block Size : 데이터 또는 프로그램의 한 블록 크기이며, 정보를 처리하는 논리적인 단
- 위로 보통 레코드의 집합으로 구성됨.
- Time : 마지막으로 수정된 날짜, 시간

**Comment by jungueheon** [comment]
### 2-1. struct stat* : 파일의 정보가 들어가는 구조체 포인터
struct stat {
dev_t st_dev; /* ID of device containing file /
ino_t st_ino; / inode number /
mode_t st_mode; / protection /
nlink_t st_nlink; / number of hard links /
uid_t st_uid; / user ID of owner /
gid_t st_gid; / group ID of owner /
dev_t st_rdev; / device ID (if special file)
off_t st_size; /* total size, in bytes /
blksize_t st_blksize; / blocksize for file system I/O /
blkcnt_t st_blocks; / number of 512B blocks allocated /
time_t st_atime; / time of last access /
time_t st_mtime; / time of last modification /
time_t st_ctime; / time of last status change */
};

**Comment by jungueheon** [comment]
### 2-2. 필요한 정보
struct stat {
off_t st_size; //파일의 총 크기
blkcnt_t st_blocks; //512Byte block의 개수
time_t st_mtime; //마지막 수정 시간
};

**Comment by tennisjeong** [comment]
수고많았습니다.

**Comment by jungueheon** [comment]
감사합니다.
