### ISSUE TITLE
3. 관련 함수

### ISSUE THREAD

**Issue by jungueheon** [naniboy/Project2#9]
- 정보 : stat() = 파일의 정보를 받아오는 함수.
- 시간 : localtime() = time_t값을(calender time) broken-down time으로 바꿔주는 함수.

**Comment by jungueheon** [comment]
### 3-1. stat() 함수
### 기본 형 : int stat(const char *path, struct stat *buf);

- const char *path : 파일의 경로
- struct stat *buf : 파일의 정보가 들어가는 구조체

**Comment by jungueheon** [comment]
### 3-2. localtime() 함수
### - 기본 형 : struct tm *localtime(const time_t *temp);
### - const time_t *temp : time_t형 변수를 가리키는 포인터
위 stat()함수로 정보를 받아온 후 인자로 사용한다.

### - struct tm* localtime : 시간 정보가 들어가는 구조체 포인터
struct tm* localtime{
int tm_sec; /* seconds /
int tm_min; / minutes /
int tm_hour; / hours /
int tm_mday; / day of the month /
int tm_mon; / month /
int tm_year; / year */
}

**Comment by jungueheon** [comment]
테스트 결과
![image](https://user-images.githubusercontent.com/33748824/39989328-9a558324-57a4-11e8-8185-988461bef18f.png)

**Comment by naniboy** [comment]
![image](https://user-images.githubusercontent.com/33748813/39990086-b077096e-57a6-11e8-8fdd-24198479df8e.png)

여기서 에러가 떠서 확인해보니까
포인터 2개가 같은 값을 갖게 되던데 이유 아시나요?

**Comment by naniboy** [comment]
죄송합니다. 
해결했습니다.
